# Generated by Django 3.2.7 on 2021-10-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageconverted', models.ImageField(blank=True, null=True, upload_to='converted/')),
                ('photooriginal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.photos')),
            ],
        ),
    ]
