# Generated by Django 3.2.7 on 2021-10-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_convertedphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertedphotos',
            name='id',
        ),
        migrations.AddField(
            model_name='convertedphotos',
            name='timestampcreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='convertedphotos',
            name='photooriginal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.photos'),
        ),
    ]
