# Generated by Django 3.2.7 on 2021-10-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211003_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedphotos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convertedphotos',
            name='photooriginal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.photos'),
        ),
    ]
